//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstLearn.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_inventory
    {
        public int Id { get; set; }
        public string ConstCode { get; set; }
        public string SpoolSpec { get; set; }
        public string SteelSpec { get; set; }
        public string LR { get; set; }
        public Nullable<int> AgingTime { get; set; }
        public Nullable<int> AllNumber { get; set; }
        public Nullable<int> NowNumber { get; set; }
        public Nullable<int> OvertimeNumber { get; set; }
    }
}
