//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstLearn.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_outdetail
    {
        public int Id { get; set; }
        public Nullable<int> PackageOutboundWorkTaskId { get; set; }
        public Nullable<int> OutOrder { get; set; }
        public string SpoolCode { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string InWarehouseTime { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
